name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Run Build
        run: |
          hatch env create
          hatch build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Run Test
        run: |
          hatch env create test
          hatch test
